version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5003:5000"

  frontend:
    build: ./frontend
    container_name: node_frontend
    ports:
      - "3000:3001"
    depends_on:
      - backend
